[package]
name = "validator"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.44.2", features = [ "csv", "lazy","strings"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
csv = "1.3.1"
bio-seq = "0.13.5"
